/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WallData } from "./types";

export const EXHIBITION_WALLS: WallData[] = [
  {
    id: 0,
    nameZh: "Section1：奇石的生成",
    nameEn: "North Wall: Whisper of Nature",
    direction: "N",
    descriptionZh: "探索大自然億萬年經風沙、地質作用自然生成的造型，與人類巧思與歷史文化的完美融合。",
    descriptionEn: "Explore natural formations sculpted over millions of years by geologic force and wind, alongside human craftsmanship and cultural stories.",
    wallColor: "bg-gradient-to-b from-[#f5f5f0] to-[#eaeae2]",
    artworks: [
      {
        id: 1,
        title: "《肉形石》",
        artist: "清代宮廷御用工匠",
        year: "清代 (Qing Dynasty)",
        imageUrl: "/input_file_0.png",
        descriptionZh: "《肉形石》為清代宮廷珍玩，材質為碧石（玉髓類石英）。工匠敏銳捕捉碧石的天然層理，由上至下染出由深至淺的褐色滷汁光澤。最為稱道的是在頂部加工出無數細小凹點，逼真模擬豬皮毛細孔，成功將堅硬的似玉美石，雕琢出剛起鍋時東坡肉表皮鬆軟且富彈性的視覺質感，堪稱華夏「人與美石」巧雕工藝的巔峰代表作。（現藏於國立故宮博物院）",
        descriptionEn: "The Meat-shaped Stone, structured from jaspar (chalcedony), is a signature masterpiece from the Qing Dynasty court. Craftsmen ingeniously aligned the stone's mineral bands, staining it from top to down to mimic flavorful soy-brined gravy. Outstandingly, they drilled tiny pores on top to emulate pig-skin textures, transforming the rugged stone into succulent visual braised pork.",
        wallId: 0,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(197, 168, 128, 0.15)",
        audioScript: "您好，歡迎欣賞一號展品《肉形石》。這件被尊為故宮三寶之一的奇珍，其原料是純天然的碧石。工匠順應其天然的層理紋路，施以精妙的染色工藝，完美呈現肥瘦相間的滷肉層次。最神奇之處在於頂部的豬皮，工匠細心戳出微小凹孔做為毛細孔，使人防不勝防地產生「肥而不膩、鬆軟Q彈」的錯覺。這正是大自然與人類巧雕藝術的巔峰共鳴。"
      },
      {
        id: 2,
        title: "《肉形石‧探秘》",
        artist: "地質與工藝解密",
        year: "現代 (Modern Study)",
        imageUrl: "/input_file_1.png",
        descriptionZh: "肉形石的原料為天然碧石瑪瑙，歷經漫長的地質作用而形成。礦物受到雜質與環境變化影響，逐漸產生深淺交錯的層理與色帶。工匠順應其天然紋理進行細緻修飾與染色，使紅褐色調更加鮮明。同時表面細密的凹點結構也巧妙營造出近似豬皮毛孔的質感，展現了大自然鬼斧神工與人類工藝智慧的結合。",
        descriptionEn: "This exhibit decodes the natural origin of the Meat-shaped Stone. Formed through ancient geothermal crystallization, impurities generated realistic layers of fat and meat. Skilled artisans followed these contours, enhancing the reddish-brown color to stimulate immediate food associations, celebrating the fusion of organic art and humanity.",
        wallId: 0,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(180, 100, 80, 0.12)",
        audioScript: "這裡是二號展品《肉形石‧探秘》的導覽。我們在這裡深入石頭的成因。在億萬年前的地殼變動中，二氧化矽溶膠滲入岩石裂隙，並夾雜了不同的金屬礦物，從而形成了這般色彩豐富、條紋分明的瑪瑙與碧石。工匠在此基礎上進行畫龍點睛的點綴，證明最偉大的藝術，永遠都在於與大自然的順應、對話，而非粗暴重塑。"
      },
      {
        id: 3,
        title: "《歲月》",
        artist: "大自然鬼斧神工",
        year: "億萬年自然刻蝕",
        imageUrl: "/input_file_2.png",
        descriptionZh: "《歲月》是一件天然奇石，材質為戈壁瑪瑙，產地為內蒙古蘇宏圖。這塊瑪瑙歷經億萬年風沙刻蝕，石表自然形成酷似滄桑老者之面容。其額紋深陷、眼窩生動，彷彿一位靜觀滄海桑田的智者，將抽象的「時間」具象化為不朽的岩石藝術，為大自然鬼斧神工之作。",
        descriptionEn: "Sculpted by Gobi desert winds over hundreds of millions of years, this natural Gobi Agate resembles the facial contours of an elder. With sunken temples and expressive eyes, it personifies the abstract concept of Time itself into immortal stone art, created entirely without human carving.",
        wallId: 0,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(120, 110, 95, 0.15)",
        audioScript: "您好，現在為您播報三號展品風沙結晶《歲月》。這是一顆純天然的戈壁瑪瑙，產自內蒙古寬廣荒涼的蘇宏圖。它沒有經過任何人工雕琢，完全是上億年來乾旱沙漠中，強烈風沙磨礪與溫差交替刻蝕出的奇蹟。看它那皺褶的額頭，深邃的眼底，彷彿一位沈思億萬年歷史演變的智者，告訴著我們，在歲月面前，頑石亦生長出了不朽的靈魂。"
      },
      {
        id: 4,
        title: "《歲月‧老奶奶石》",
        artist: "歲月與自然觀察",
        year: "地質史 (Geological Chronicle)",
        imageUrl: "/input_file_3.png",
        descriptionZh: "這顆戈壁石在地質運動、礦物沉積與長期風化的共同作用下，恰好形成接近人臉的結構比例（額頭、眼窩、鼻樑與嘴角），使它超越了單純的石頭形態，展現出極強的擬人化特徵與神韻。皺褶紋理如同時間留下的記號，因此被稱為「老奶奶石」。",
        descriptionEn: "Also affectionately known as 'The Grandmother Stone', this Gobi marvel illustrates how random forces of nature can organize mineral profiles into highly expressive human likenesses. The mineral veins stretch out like wisps of graying hair, lending a touch of human warmth and vulnerability to cold stone.",
        wallId: 0,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(150, 140, 120, 0.1)",
        audioScript: "歡迎收聽四號展品《歲月‧老奶奶石》的解說。在內蒙古的寒暑變遷中，隨著岩石硬度微小差異，風沙削去了較軟部分的表皮，而留下了突出的骨骼與額骨形狀。表面交錯的細線，也恰似老奶奶臉上的皺紋。這種巧合，在赏石文化中又叫「神韻」。大自然是一位無比浪漫的雕塑家，用幾億年的時間，在風沙中為我們留下了時光的肖像。"
      }
    ]
  },
  {
    id: 1,
    nameZh: "東面牆 ── Section2 尋找自己的價值吧",
    nameEn: "East Wall ── Section 2: Find Your Own Value",
    direction: "E",
    descriptionZh: "探尋形像與價值的深層意涵。透過不同的視角與正確的修造，在石頭、萬物以及人的身上，尋回那最美、最寶貴的生命型態。",
    descriptionEn: "Discover the deeper meaning of image and value. Through varying perspectives and active self-making, find the most beautiful and precious forms of life.",
    wallColor: "bg-gradient-to-b from-[#fdfbf7] to-[#f5f1e9]",
    artworks: [
      {
        id: 5,
        title: "01 形像石",
        artist: "SECTION 02",
        year: "自然與啟發 (Nature & Inspiration)",
        imageUrl: "/input_file_4.png",
        descriptionZh: "「大家仔細看看這顆石頭，有什麼想法呢？」此作品展示了一顆天然的巨大岩石，外觀有深淺凹槽與起伏。從特定角度觀看，它帶有神秘而獨特的形體特徵，引導觀展者開始思考及觀察大自然造物與人生命價值的連結。",
        descriptionEn: "\"Look closely at this stone. What thoughts come to your mind?\" This piece showcases a natural, massive rock with textured recesses and contours, inviting viewers to ponder its unique form and begin their journey of discovering hidden values.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(180, 140, 100, 0.15)",
        audioScript: "歡迎來到第二展區「尋找自己的價值吧」。請大家仔細看看第一號展品《形像石》。這是一顆矗立於綠茵之上的天然巨石，表面佈滿了起伏不平的輪廓與深淺不一的凹槽。大家靠近、仔細端詳一下這顆石頭，它讓您聯想到了什麼？有什麼想法呢？大自然常在不經意間隱藏著奧秘，讓我們帶著好奇心，繼續往下探索吧。"
      },
      {
        id: 6,
        title: "02 你看出來了嗎？",
        artist: "SECTION 02",
        year: "視角觀察 (Observational Angle)",
        imageUrl: "/input_file_5.png",
        descriptionZh: "「從另一個角度看出哪個形象呢？」同一顆石頭，當我們轉換位置，從另一個側面去觀看時，會展現出與剛才截然不同的線條與神態。這件作品啟示我們：觀察事物不能僅憑單一面向。",
        descriptionEn: "\"Can you see it from another side? Which image emerges from this new angle?\" The exact same stone, when viewed from another position, reveals entirely different lines and expressions, showing that understanding requires multiple viewpoints.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(130, 140, 110, 0.12)",
        audioScript: "請看二號展品《你看的出來了嗎？》。我們換了另一個位置，重新端詳剛才那一顆石頭。您注意到了嗎？這時，它的上半部分隆起、一側帶著柔和的弧度，是不是展現出了截然不同的形象？它教導我們，僅從單一面向下定論，往往會使我們錯失事物更深層的本質。請試著在心中揣摩，這新的角度帶給您怎樣的新發現？"
      },
      {
        id: 7,
        title: "03 從正確的角度來看",
        artist: "SECTION 02",
        year: "價值格言 (Value Maxim)",
        imageUrl: "/input_file_6.png",
        descriptionZh: "「同一顆石頭，會因觀看的角度不同，而看見完全不同的形像。」因為之前只從「這面」來看那石頭，才說那是「那個形像」的石頭。後來換著角度從「那面」看，就在同一顆石頭上看到了不同的形像。不論是看萬物還是看人，評價都會隨著觀看的位置和角度左右，看起來是好看還是不好看。",
        descriptionEn: "\"The exact same stone, due to different viewing angles, will reveal completely different images.\" Whether observing all creation or looking at people, evaluations always shift depending on our position and perspective—dictating whether something appears beautiful or pleasant.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(190, 170, 140, 0.15)",
        audioScript: "歡迎聆聽三號展品《從正確的角度來看》的語音導覽。格言說道：「同一顆石頭，會因觀看的角度不同，而看見完全不同的形像。因為之前只從這面看，才判定它是某種模樣的石頭；一旦換個角度，卻在同一顆石頭看見了全新形體。不論是看萬物還是看人，都是一樣的。我們往往會被觀看者的位置與角度所左右，進而影響了美醜與好壞的評價。因此，尋找真正的價值，需要我們站在正確的位置與視角。」"
      },
      {
        id: 8,
        title: "04 最棒的形像",
        artist: "SECTION 02",
        year: "大象石啟示 (Revelation of Elephant Rock)",
        imageUrl: "/input_file_7.png",
        descriptionZh: "「因為某個角度有『最棒的形像』，要從『那個角度』正確地來看，也才能看到最棒的價值。」〈大象石〉也是一樣，根本形像是「大象形像」。要從某個角度、正確地看，才能確實看出那是「大象的形像」。也因為正確地看出那形像後，體會到這顆石頭更寶貴。每個人，也都有屬於自己的「最棒的形像」。",
        descriptionEn: "\"Because a certain angle holds the 'best image', we must look correctly from 'that angle' to perceive its supreme value.\" Just like the Elephant Stone, which truly embodies the image of an elephant when viewed from the correct angle, every individual has their own \"best image\" waiting to be discovered.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(175, 135, 100, 0.15)",
        audioScript: "這是四號展品《最棒的形像》。格言寫著：「因為某個角度有最棒的形像，要從那個角度正確地來看，才能看見最棒的價值。大象石也是如此，它的根本形像其實是一隻栩栩如生的大象，但必須從某個特定的、正確的視角，才能看清大象的外貌。一旦看清了，它的獨特與寶貴就油然而生。人也是這樣，每個人都有一個最完美的視角，在那裡，你擁有著屬於自己最棒、最無可取代的形像。」"
      },
      {
        id: 9,
        title: "05 象徵福氣的石頭",
        artist: "SECTION 02",
        year: "生命形象 (Symbol of Blessings)",
        imageUrl: "/input_file_8.png",
        descriptionZh: "「大家看得出來它有哪八個部分相似於蟾蜍嗎？」這顆天然的青灰色巨石被稱作「蟾蜍石」或「象徵福氣的石頭」，其橫臥的形態、粗糙的表皮及前凸的吻部，極為神似一隻蹲伏的蟾蜍。作品傳達：世間萬物皆有其對應與寄寓之美。",
        descriptionEn: "\"Can you detect which eight parts of this stone resemble a toad?\" This natural dark gray stone, symbolizing blessings, lies horizontally. Its rugged texture and crouched contour call to mind the shape of a toad, bringing auspicious sentiments.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(110, 130, 140, 0.12)",
        audioScript: "請前來觀看五號展品《象徵福氣的石頭》。這是一顆青灰色的臥石，傳說中它是一隻帶來福祿的石蟾蜍。請大家發揮您的觀察力，仔細端詳一下：您能找出這顆石頭有哪八個部分跟生動的蟾蜍驚人地相似嗎？大自然把生命的痕跡烙印在磐石上，當我們看出了它生動的形態，便賦予了它充滿祝福的靈性與意義。"
      },
      {
        id: 10,
        title: "06 越相似，越有價值",
        artist: "SECTION 02",
        year: "自我造就 (Self-refinement)",
        imageUrl: "/input_file_9.png",
        descriptionZh: "「相似於 神想法、言語及行為而輪廓鮮明之人，是『以人的身分成為神的人』。」石頭只要有「一個好看的地方」，就算整體不好看，仍會是「最昂貴的石頭」。人也是一樣，只要有「一個最好的優點」，就會成為「最寶貴的存在」。人越是全方位具備並造就，就越是理想。",
        descriptionEn: "\"Those whose thoughts, words, and actions closely resemble divine ideals stand out with distinct contours, walking as precious mirrors of the highest goodness.\" A stone with just 'one beautiful feature' remains valuable despite flaws. Likewise, a person with 'one core virtue' is infinitely precious, and all-round self-making brings closer to the ideal.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(185, 150, 110, 0.15)",
        audioScript: "歡迎聆聽六號展品《越相似，越有價值》。這裡的深刻啟示提到：「相似於最高想法、言語及行為而輪廓鮮明之人，是用人的身分彰顯了神性尊貴的人。正如奇石，只要有一個部分長得極美、極有特色，即使其他地方不盡完美，它依然是熱門且昂貴的珍寶。人也是如此，只要發揚、造就出自己身上一個最棒的優點，就能讓自己成為世上最珍貴的存在。而若能在各面向全方位造就，就更趨近理想境界了。」"
      },
      {
        id: 11,
        title: "07 〈福〉",
        artist: "SECTION 02",
        year: "行動與實踐 (Blessing & Action)",
        imageUrl: "/input_file_10.png",
        descriptionZh: "「人生，行動多少，就能得到多少；努力奔跑，就能快速前行，興起神蹟。」若去尋找，就能發現生活中處處都有成堆的祝福隨行為而來，應藉由行動將它找出來。若想得到龐大且永恆的祝福，就要尋找神永恆之手、永恆之事，付諸實踐。",
        descriptionEn: "\"In life, you receive in direct proportion to your action. By running diligently, you move forward rapidly to witness miracles.\" Blessings are stacked high in daily life, following our deeds—we must actively unearth them. To obtain grand and eternal blessings, align with eternal purpose and practice it.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(200, 180, 150, 0.15)",
        audioScript: "這是七號展品《福》的詩作。詩中說：「人生，行動多少，就能得到多少。努力奔跑，就能快速前行、興起神蹟。只要你邁開腳步去尋找，就會驚訝地發現，日常生活中處處都堆疊著因你的行動所帶來的祝福。若想獲得那最宏大且永恆的福氣，就不能只看眼前，而是要尋求永恆之事，並在生活中付諸實踐。」"
      },
      {
        id: 12,
        title: "08 〈要修造〉",
        artist: "SECTION 02",
        year: "生命開發 (Development of Life)",
        imageUrl: "/input_file_11.png",
        descriptionZh: "「好山、好水、好亭子，什麼條件都具備的地方，哪裡有呢？」若具備了一兩樣，其餘的就要修造，就要開發。人生與環境，皆是如此。這首詩鼓勵我們積極投入自我開發與修繕，主動打造理想的人格與生命環境。",
        descriptionEn: "\"Great mountains, pure waters, elegant pavilions–where resides a place equipped with every perfect condition?\" Even if nature grants one or two, the rest must be built and developed. In life as in our surroundings, active cultivation fulfills our highest potential.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(195, 165, 130, 0.15)",
        audioScript: "現在播報八號展品《要修造》的語音。詩人寫道：「好山、好水、好亭子，什麼條件都合意、具備的地方，世上哪裡有呢？即使在名勝之地，如果具備了一兩樣天然好景，其餘的舒適與美好，仍需要人們精心修造與開發。我們的人生、心靈與所處的環境，全都是這個道理。美好的價值從來不是憑空現成，而是透過我們一點一滴、積極親手開發出來的。」"
      },
      {
        id: 13,
        title: "09 計畫性造就自己",
        artist: "SECTION 02",
        year: "自我栽培的法則 (Law of Self-Cultivation)",
        imageUrl: "/input_file_12.png",
        descriptionZh: "計畫性地造就並栽培自己吧！這世上的一切事物，越造就，就會越「值錢」、越「發光」。<自己的人生>也是一樣，會隨著如何製造而左右是否值錢且發光。如果造就自己後再使用，就可以使用得比造就之前更有意義、更有價值一萬倍、十萬倍、一百萬倍。不論是誰都擁有肉、內心、精神、魂與靈，所以一切都左右於自己如何造就。假如沒有造就自己，就會度過百倍、千倍充滿各種痛苦和困難的生活。所以就算辛苦也要造就<自己>才行。",
        descriptionEn: "Cultivate and develop yourself with intention: Everything in the world shines brighter and gains value through active refinement. Life is no exception—one's ultimate worth depends on intentional crafting. Every human possesses a body, heart, spirit, mind, and soul, and the quality of one's experience is entirely determined by how one shapes oneself.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(180, 160, 140, 0.15)",
        audioScript: "這是九號展品《計畫性造就自己》的解說。格言叮嚀我們：首先，要有計畫地造就並栽培自己。世界上的一切，經過雕琢與造就後，均能大幅提升價值而散發光芒。我們的人生亦是同理。如果先將自己鍛鍊、造就完全再去實踐人生，我們發揮出的自我價值，將會比先前提升萬倍、甚至百萬倍。每個人都有肉體、精神、心靈與靈魂，這一切不凡的主宰權，都在於我們願意付出汗水來雕琢自己。即使過程艱辛，也是避免日後陷入迷茫挫折的最佳良師，我們必須全方位造修自己。"
      },
      {
        id: 14,
        title: "10 完美的管理與修煉",
        artist: "SECTION 02",
        year: "內心意志與實踐 (Will and Mind Alignment)",
        imageUrl: "/input_file_13.png",
        descriptionZh: "雖然有人會按照原本存在的狀態來管理，但真正的管理是「造就得更好、更發光」。神將人和肢體都創造得很完全。因此，每個人都要將內心和想法造就完全再行動。人會隨著擁有多麼強大的決心、多麼全心全意地深入思考而改變自己的命運。如果與神、聖靈和主成為一體，內心就會變得完全，內心會變得強韌。只要下定決心，內心瞬間就會變強。不論自己生活、生命栽培、自我造就或一切萬事，首先都要完美地構想，之後再按照那構想慢慢地、完全地實踐。",
        descriptionEn: "Perfect alignment of mind, will, and action: True management is not merely maintaining, but refining to shine brighter. Destiny is shaped by deep, unwavering resolve. Act completely upon perfect visions to raise your life to its highest stellar glow, realizing your potential like the sun, moon, or stars.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(170, 150, 130, 0.15)",
        audioScript: "歡迎聆聽十號展品《完美的管理與修煉》。格言指出：真正的管理並非一成不變，而是要在現有的基礎上，「造就得更好，讓它更發光」。我們的心思意念與行動，都要先深思熟慮，完美地構想好藍圖，然後不急不躁、完全地去實踐。內心的意志極為關鍵，只要下定頑強的決心，內心瞬間就能披上堅韌的盔甲。人生的光芒可如繁星、可如明月、甚至溫暖如烈日，而這一切的高低與境界，完全取决于我們究竟造就了自己多少。"
      },
      {
        id: 20,
        title: "11《復活很重要》",
        artist: "SECTION 03",
        year: "靈命修持 (Resurrection & Renewal)",
        imageUrl: "/input_file_11.png",
        descriptionZh: "「復活真的很重要，若不復活，就只得用原本陳舊的生活度過。所以就算遇到辛苦與磨難，也要使自己的內心與心靈復活，走向更高的生命層次！」",
        descriptionEn: "Resurrection is key; without it, we merely cycle through old ways. Even through hardship, revive your inner spirit to reach the peak of life.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(160, 150, 140, 0.12)",
        audioScript: "歡迎欣賞展品《復活很重要》。這裡寫道：復活真的非常重要！如果生活、想法和精神不復活的話，我們就只能停留在以往平凡、低等且充滿框架的生活中。因此，即使生活中遇上辛苦、困難或是再大的風浪，我們也一定要振作起精神，下定決心讓自己的內心與意志復活！唯有讓生命復活的人，才能迎來充滿希望與榮耀的新生活。"
      },
      {
        id: 21,
        title: "12 人生命運的建造",
        artist: "SECTION 03",
        year: "命運法則 (Destiny via Cultivation)",
        imageUrl: "/input_file_12.png",
        descriptionZh: "「人會隨著擁有多麼強大的決心、多麼全心全意地深入思考而改變自己的命運。15. 人像所建造 self-making 的方法與使用。16. 人的肉體有一天必會衰老，所以更要在此生努力造就、發展並修煉自己永恆的魂與靈。18. 不要焦慮！只要不斷按部就班地磨煉自己、造就自己，就能走向最高級的人。」",
        descriptionEn: "Destiny shifts based on determination. While the physical shell ages, nurturing our eternal spiritual self through consistent step-by-step building makes us complete.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(150, 160, 150, 0.1)",
        audioScript: "請聆聽第十二項展品《人生命運的建造》。格言提醒：人的肉體隨著時間的流逝，有一天必然會老去。然而，我們內在的魂與靈卻是可以透過磨煉與修築，臻至永恆榮美。不要焦急、更不要氣餒！對自我的造就就如同建造摩天大樓，只要有信念，我們就能在日常的每一天，一層一層穩固地將自我的大廈起造起來，終將蛻變為極富深度與光芒的生命。"
      },
      {
        id: 22,
        title: "13 教育與生命變化",
        artist: "SECTION 03",
        year: "啟蒙之道 (Transformation through Learning)",
        imageUrl: "/input_file_13.png",
        descriptionZh: "「19. 造就就是『透過教育使生命變化』。20. 造就如同『將粗糙的岩石修琢成型，進而成為最高級的人』。24. 不只造就肉體的習慣，更要將內心想法、精神理念、思考靈感，與永恆之魂一併深刻地造就，如此才能在日常中展現最高價值的靈氣神采！」",
        descriptionEn: "Cultivation means transformation through learning. Elevating not just bodily habits but thoughts and spirit creates an exquisite and fine-tuned life with supreme purpose.",
        wallId: 1,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(140, 160, 170, 0.12)",
        audioScript: "歡迎欣賞第十三項展品《教育與生命變化》。什麼是造就？造就就是透過不斷豐富的心靈思考與學習教育，使生命產生根本的、美麗的變化。如同將一塊粗糙平凡的荒野原石，仔細雕琢成受人景仰的藝術品。這不僅是鍛煉身體的良好作息習慣，更要把我們的思維格局、精神理念與善良意志一併雕琢造就。如此，在我們日常的一言一行中，都將散發出溫暖且崇高的光芒。"
      }
    ]
  },
  {
    id: 2,
    nameZh: "南面牆 ── 人間容顏與百態",
    nameEn: "South Wall ── Human Faces & Everyday Life",
    direction: "S",
    descriptionZh: "凝視街頭巷尾與日常瞬間，捕捉光影倒影與真實臉龐背後，最溫柔而真摯的人性溫度。",
    descriptionEn: "Observing everyday moments and street reflections, capturing the warm and authentic human connection behind glowing faces.",
    wallColor: "bg-gradient-to-b from-[#faf5f0] to-[#eae0d5]",
    artworks: [
      {
        id: 15,
        title: "午後的虹彩倒影",
        artist: "Sophie Mercier (蘇菲·梅西耶)",
        year: "2023",
        imageUrl: "https://images.unsplash.com/photo-1515621061946-eff1c2a352bd?q=80&w=800",
        descriptionZh: "描繪雷陣雨過後的暗黑瀝青路面，雨水坑中倒映著整座城市斑斕交疊的霓虹店招，宛如落在凡間的炫目虹彩與星空。",
        descriptionEn: "Capturing a wet Parisian asphalt street after a heavy thunderstorm, where glowing neon shop signs break up and dissolve within a puddle, creating a beautiful spectrum of color.",
        wallId: 2,
        hasAudioGuide: true,
        aspectRatio: "landscape",
        accentColor: "rgba(168, 85, 247, 0.15)",
        audioScript: "正在播放六號作品《午後的虹彩倒影》導覽。蘇菲·梅西耶是一位熱愛捕捉城市碎片瞬間的藝術家。二零二三年夏天，在一場午後雷陣雨過後，她發現巴黎街頭的人行道水坑裡，各色店招的霓虹燈正像彩虹般碎裂、融合，鋪陳在深黑的瀝青上。這幅畫就是在告誡現代都市中步履匆匆的我們：即便是踩在最卑微的雨水與泥沙之上，只要低頭細看，世界依然回饋給我們一整片星空般炫目的色彩。"
      },
      {
        id: 16,
        title: "都市星塵與微笑",
        artist: "Ethan Hunt (伊森·亨特)",
        year: "2019",
        imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800",
        descriptionZh: "這張特寫人像充滿了不可抵擋的溫暖能量。女孩在紛繁都市的虛焦微光中綻放燦爛笑容，眼神中躍動著星光，象徵市井塵囂中那份最真摯而永恆的快樂。",
        descriptionEn: "An infectious close-up brimming with pure warmth. The subject's brilliant laugh pops beautifully against a creamy bokeh background of city traffic lights, reminding us of genuine happiness in the concrete jungle.",
        wallId: 2,
        hasAudioGuide: true,
        aspectRatio: "square",
        accentColor: "rgba(20, 184, 166, 0.15)",
        audioScript: "七號作品《都市星塵與微笑》歡迎您。這幅寫實肖像由伊森·亨特創作。畫面中的女孩有著燦爛無比、富有感染力的笑容，背景是紐約繁星般的車尾燈與霓虹耀斑。藝術家刻意將背景大幅度虛化，讓這份溫柔而堅定的人性喜悅成為畫面的唯一焦點。它像是一股冬日暖流，融化了鋼筋水泥城市帶來的冷漠與孤寂。"
      }
    ]
  },
  {
    id: 3,
    nameZh: "西面牆 ── 構築與光影幾何",
    nameEn: "West Wall ── Architectural & Light Play",
    direction: "W",
    descriptionZh: "探尋人造結構、混凝土、玻璃與自然光影之間的深邃契合。重塑幾何線條的和諧共振。",
    descriptionEn: "Unearthing the deep spatial dialogue between concrete, glass, and sunbeams. Reimagining the visual symphony of architectural scale.",
    wallColor: "bg-gradient-to-b from-[#f0f3f5] to-[#e1e6eb]",
    artworks: [
      {
        id: 17,
        title: "清水混凝土的和諧樂章",
        artist: "Zaha Novak (扎哈·諾瓦克)",
        year: "2022",
        imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800",
        descriptionZh: "展現現代清水模建築極具張力的傾斜立面。在特定时刻，晨光以斜角四十五度切入中庭，在灰色混凝土表面畫出強烈的光影長矛，冷靜、力量且純粹。",
        descriptionEn: "Depicting an angled facade of minimalist fair-faced concrete. Under a specific hour, sunlight cuts down the atrium at 45 degrees, casting sharp, dramatic geometric shadows like spears.",
        wallId: 3,
        hasAudioGuide: true,
        aspectRatio: "landscape",
        accentColor: "rgba(71, 85, 105, 0.15)",
        audioScript: "歡迎移步至八號作品《清水混凝土的和諧樂章》。著名建築美學繪畫家扎哈·諾瓦克在二零二二年繪製了這幅巨作。作品聚焦在安藤忠雄風格的極簡混凝土牆面上，清晨的陽光如同一柄銳利的長矛斜刺而入，光與影將平整的灰色牆面分割成數個黃金三角比例。這沒有多餘裝飾的空間，正是利用了「空」與「光」本身，讓建築得以在寂靜中唱出悠揚的和聲。"
      },
      {
        id: 18,
        title: "裂隙之內即是天堂",
        artist: "Lucas Thorne (盧卡斯·索恩)",
        year: "2024",
        imageUrl: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?q=80&w=800",
        descriptionZh: "這幅極限對比構圖描繪了高聳入雲的黑色峽谷式高樓群夾縫。中央的一線狹窄天空中呈現出絢麗的粉紫晚霞，象徵在巨大的鋼鐵森林深處，人們依然對星空與自由保有的浪漫渴望。",
        descriptionEn: "A dramatic vertical layout of monolithic dark skyscrapers forming a chasm. Trapped in the narrow vertical sky in-between is a magnificent violet sunset, symbolizing the persistent human romance for freedom.",
        wallId: 3,
        hasAudioGuide: true,
        aspectRatio: "portrait",
        accentColor: "rgba(236, 72, 153, 0.15)",
        audioScript: "現在正為您導覽九號作品《裂隙之內即是天堂》。這件索恩的攝影壓克力壓塗畫作，描繪了東京摩天大樓之間如同一線天般的恐怖峽谷。高樓牆面是近乎純黑的碳纖維質感，而在兩座宏偉幾何體之間的狹窄天空中，卻燃燒著極其溫柔瑰麗、深紅夾雜夢幻紫色的晚霞。這道裂縫彷彿在提醒迷失在朝九晚五大樓底層的我們：裂痕所在的地方，正是光線照射進來、通往夢想與天堂的唯一出口。"
      },
      {
        id: 19,
        title: "向未來而立的紀念碑",
        artist: "Jean-Luc Picard (皮卡特)",
        year: "2023",
        imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800",
        descriptionZh: "全玻璃帷幕大樓筆直插入蔚藍天際，折射出無雲天空的深邃與白晝烈陽的奪目光芒。象徵人類理智、科技探索的高峰，以及宏偉工程的現代紀念碑。",
        descriptionEn: "A towering blue-glass skyscraper piercing directly into the pristine sky, reflecting clouds and sun flare. This celebrates the heights of human engineering and the clean monuments of a technological future.",
        wallId: 3,
        hasAudioGuide: true,
        aspectRatio: "square",
        accentColor: "rgba(14, 165, 233, 0.15)",
        audioScript: "您好，歡迎聆聽十號作品《向未來而立的紀念碑》。藝術家皮卡特在二零二三年用這幅大膽的仰角構圖，致敬了人類現代工程之美。玻璃幕牆完美地折射出蔚藍的天空，極富速度感的銀白色鋼樑直衝九霄。這座高聳的大樓在此刻不再只是一個辦公大廈，而是一座展現人類智慧、勇氣與渴望向天空無垠探索的現代圖騰。"
      }
    ]
  }
];
